services:
  - type: web
    name: sebb-ai
    env: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: RAILS_ENV
        value: production
      - key: RAILS_MASTER_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: sebb-ai-db
          property: connectionString
      - key: SEBB_AI_DATABASE_PASSWORD
        fromDatabase:
          name: sebb-ai-db
          property: password
      - key: RAILS_SERVE_STATIC_FILES
        value: true
      - key: RAILS_LOG_TO_STDOUT
        value: true
    databases:
      - name: sebb-ai-db
        databaseName: sebb_ai_production
        user: sebb_ai
        plan: free
    plan: free
    region: oregon
    buildCommand: |
      bundle install
      npm install
      SECRET_KEY_BASE_DUMMY=1 bin/rails assets:precompile
    startCommand: bin/rails server -b 0.0.0.0 -p $PORT 